
spring:
  profiles:
    active: local

  redis:
    host: 127.0.0.1
    port: 6379
    password: redis6379
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0   # 连接池中的最小空闲连接

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: 2000
    maximum-pool-size: 20
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/qinyi?serverTimezone=Asia/Shanghai&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: mysql

# MYBATIS PROPERTIES
      mybatis-plus:
        check-config-location: true
        # 如果xml文件在类路径下则需要添加包名 classpath*:com/demo/mybatisplus/mapper/**/*.xml 且 pom.xml 在加上 resource 配置
        # 如果xml文件在 resources 下则为 mapper/**/*.xml
        mapper-locations: classpath*:mapper/**/*.xml
        type-aliases-package: com.demo.mybatisplus.entity
        configuration:
          cache-enabled: true
          lazy-loading-enabled: true
          aggressive-lazy-loading: true

  global-config:
    db-config:
      # 全局主键自增策略
      id-type: auto
      # 全局表前缀配置
      table-prefix: "t_"

logging:
  config: classpath:log4j2.xml
  level:
    com.demo.mybatisplus.mapper: debug